In [85]:
import numpy as np
import scipy.optimize
from scipy.optimize import Bounds


def rebalance_add_only(money,state,objective=[0.8,0.1,0.1]):
    bounds = Bounds(np.array([0]*len(state)), np.array([np.inf]*len(state)))
    bounds.keep_feasible=True
    def f(x):
        return np.sum((np.array(objective)*(np.sum(np.array(state))+money) - state -x)**2)
    return scipy.optimize.minimize(fun=f,bounds=bounds,x0=np.array([money]*len(state))/len(state),constraints={'type': 'eq', 'fun': lambda x:  np.sum(x)-money})
def rebalance_take_only(money,state,objective=[0.8,0.1,0.1]):
    bounds = Bounds(np.array([-np.inf]*len(state)), np.array([0]*len(state)))
    bounds.keep_feasible=True
    def f(x):
        return np.sum((np.array(objective)*(np.sum(np.array(state))+money) - state -x)**2)
    return scipy.optimize.minimize(fun=f,bounds=bounds,x0=np.array([money]*len(state))/len(state),constraints={'type': 'eq', 'fun': lambda x:  np.sum(x)-money})
def rebalance(money,state,objective=[0.8,0.1,0.1]):
    def f(x):
        return np.sum((np.array(objective)*(np.sum(np.array(state))+money) - state -x)**2)
    return scipy.optimize.minimize(fun=f,x0=np.array([money]*len(state))/len(state),constraints={'type': 'eq', 'fun': lambda x:  np.sum(x)-money})

In [86]:
money_available = 400
current_state = [2138.73,488.77,520.14]
objective = [0.8,0.1,0.1]
with np.printoptions(precision=3, suppress=True):
    print(rebalance_add_only(money_available,current_state,objective).x)

[400.   0.   0.]


In [88]:
#to take some
money_available = -200
current_state = [2138.73,488.77,520.14]
objective = [0.8,0.1,0.1]
with np.printoptions(precision=3, suppress=True):
    print(rebalance_take_only(money_available,current_state,objective).x)

[  -0.     -84.315 -115.685]


In [91]:
#classic
money_available = 200
current_state = [2138.73,488.77,520.14]
objective = [0.8,0.1,0.1]
with np.printoptions(precision=3, suppress=True):
    print(rebalance(money_available,current_state,objective).x)

[ 539.382 -154.006 -185.376]
